//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: CFOctetSeq.h
//  Source: CFOctetSeq.idl
//  Generated: Fri Feb 05 11:36:50 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#ifndef _CFOCTETSEQ_H_
#define _CFOCTETSEQ_H_

#include "eOrb/idl_c.h"
#include "CFPrimitiveTypes.h"

namespace CF
{
   struct OctetSeq_uniq_ {};
   typedef EORBUFLSeq < OctetType, struct OctetSeq_uniq_> OctetSeq;
   typedef EORBSequence_var < OctetSeq> OctetSeq_var;
   typedef EORBSequence_out < OctetSeq> OctetSeq_out;
   extern CORBA::TypeCode_ptr _tc_OctetSeq;
}

void CF_OctetSeq_put
(
   EORB::Codec::Stream & os,
   const void * arg
);

void CF_OctetSeq_get
(
   EORB::Codec::Stream & is,
   void * arg
);





#endif 
