//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: CFPrimitiveTypes_s.cpp
//  Source: CFPrimitiveTypes.idl
//  Generated: Fri Feb 05 11:36:43 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#include "CFPrimitiveTypes_s.h"



