//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: CFPrimitiveTypes_s.h
//  Source: CFPrimitiveTypes.idl
//  Generated: Fri Feb 05 11:36:43 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#ifndef _CFPRIMITIVETYPES_S_H_
#define _CFPRIMITIVETYPES_S_H_


#include "eOrb/idl_s.h"
#include "CFPrimitiveTypes.h"


namespace POA_CF
{
}

#endif
