//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: hello.h
//  Source: hello.idl
//  Generated: Wed Feb 03 16:01:47 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#ifndef _HELLO_H_
#define _HELLO_H_

#include "eOrb/idl_c.h"

class GreetingService;

typedef GreetingService * GreetingService_ptr;
typedef EORBInterface_var < GreetingService> GreetingService_var;
typedef EORBInterface_out < GreetingService> GreetingService_out;
typedef EORBInterface_mgr < GreetingService> GreetingService_mgr;


class GreetingService
:
   virtual public CORBA::Stub
{ 
public:
   typedef GreetingService_ptr (*GreetingServiceFactory) (IOP::IOR_ptr ior);
   typedef GreetingService_ptr _ptr_type;
   typedef GreetingService_var _var_type;
   typedef GreetingService_out _out_type;

   static GreetingService_ptr _duplicate (GreetingService_ptr obj);
   CORBA::Boolean _is_a (const char * id);

   static GreetingService_ptr _narrow (CORBA::Object_ptr obj EORB_ENV_ARGN);
   static GreetingService_ptr _unchecked_narrow (CORBA::Object_ptr obj);
   static GreetingService_ptr _nil () { return 0; }
   static const char * _repository_id () { return "IDL:GreetingService:1.0"; }
   static void _assert_stub (GreetingService_ptr & obj);
   GreetingService_ptr _this () { return this; }

   virtual char * greeting (const char* greetstr EORB_ENV_ARGN) = 0;
   virtual void shutdown (EORB_ENV_ARG1) = 0;

protected:
   GreetingService () {}
   ~GreetingService () {}
private:
   GreetingService (const GreetingService &) {}
   GreetingService & operator = (const GreetingService &);
};

class GreetingService_stub
:
   virtual public GreetingService
{
public:
   GreetingService_stub (IOP::IOR_ptr ior = 0);
   GreetingService_stub (CORBA::Object_ptr p);
   ~GreetingService_stub () {}

   // Stub operations

   virtual char * greeting (const char* greetstr EORB_ENV_ARGN);
   virtual void shutdown (EORB_ENV_ARG1);
};

extern CORBA::TypeCode_ptr _tc_GreetingService;






#endif 
