//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: hello_s.h
//  Source: hello.idl
//  Generated: Fri Feb 05 11:23:39 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#ifndef _HELLO_S_H_
#define _HELLO_S_H_


#include "eOrb/idl_s.h"
#include "hello.h"

class POA_GreetingService
:
   virtual public PortableServer::ServantBase
{
public:

   virtual const char * _repository_id () const;
   CORBA::Boolean _is_a (const char * id);
   GreetingService_ptr _this (EORB_ENV_ARG1);

   virtual char * greeting (const char* greetstr EORB_ENV_ARGN) = 0;
   virtual void shutdown (EORB_ENV_ARG1) = 0;

protected:
   static void _dispatch_shutdown
   (
      void * _servant_,
      EORB::Codec::Request & _request_
      EORB_ENV_ARGN
   );
   static void _dispatch_greeting
   (
      void * _servant_,
      EORB::Codec::Request & _request_
      EORB_ENV_ARGN
   );
   virtual EORB::Codec::DispatchFN _invoke (EORB::Codec::Request & _req_ EORB_ENV_ARGN);
};


#endif
