//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: CFOctetSeq_s.h
//  Source: CFOctetSeq.idl
//  Generated: Fri Feb 05 11:36:50 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#ifndef _CFOCTETSEQ_S_H_
#define _CFOCTETSEQ_S_H_


#include "eOrb/idl_s.h"
#include "CFOctetSeq.h"
#include "CFPrimitiveTypes_s.h"


namespace POA_CF
{
}

#endif
