//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: CFOctetSeq.cpp
//  Source: CFOctetSeq.idl
//  Generated: Fri Feb 05 11:36:50 2021
//  eORB C++ V2.1.9
//  
//******************************************************************

#include "CFOctetSeq.h"




static void * CF_OctetSeq_ctor ()
{
   return new CF::OctetSeq;
}

static void CF_OctetSeq_dtor (void * arg)
{
   delete ((CF::OctetSeq*) arg);
}

void CF_OctetSeq_put
(
   EORB::Codec::Stream & os,
   const void * arg
)
{
   EORB::Codec::ParamPut p = { CORBA::_tc_OctetSeq, (void *) arg, os.m_flags };
   os.put (&p, 1UL);
}

void CF_OctetSeq_get
(
   EORB::Codec::Stream & is,
   void * arg
)
{
   EORB::Codec::ParamGet p = {CORBA::_tc_OctetSeq, arg, is.m_flags };
   is.get (&p, 1UL);
}

static void CF_OctetSeq_copy (void * dest, void * src)
{
   *(CF::OctetSeq*) dest = *(CF::OctetSeq*) src;
}

CORBA::TypeCode_ptr CF::_tc_OctetSeq;

class CFOctetSeq_plugin : public EORB::TCPlugin
{
public:

   CFOctetSeq_plugin () { EORB::TCManager::manager().add (this); };

   virtual void init (EORB_ENV_ARG1)
   {
      CF::_tc_OctetSeq = CORBA::TypeCode::build_typecode
      (
         CORBA::tk_alias,
         CF_OctetSeq_ctor,
         CF_OctetSeq_dtor,
         CF_OctetSeq_put,
         CF_OctetSeq_get,
         CF_OctetSeq_copy,
         1, 1, 0,
         0,
         0, false
      );
   }

   virtual ~CFOctetSeq_plugin ()
   {
      CORBA::release (CF::_tc_OctetSeq);
   }
};

static CFOctetSeq_plugin eorbCFOctetSeq_plugin;

