//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: CFOctetSeq_s.cpp
//  Source: CFOctetSeq.idl
//  Generated: Fri Feb 05 11:36:50 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#include "CFOctetSeq_s.h"



