//******************************************************************
// 
//  Generated by e*ORB IDL to C++ Translator
//  
//  File name: CFPrimitiveTypes.h
//  Source: CFPrimitiveTypes.idl
//  Generated: Fri Feb 05 11:36:43 2021
//  eORB C++ V2.1.9
//  
//******************************************************************
#ifndef _CFPRIMITIVETYPES_H_
#define _CFPRIMITIVETYPES_H_

#include "eOrb/idl_c.h"

namespace CF
{
   typedef CORBA::Boolean BooleanType;
   typedef CORBA::Boolean_out BooleanType_out;
   extern CORBA::TypeCode_ptr _tc_BooleanType;
   typedef CORBA::Char CharType;
   typedef CORBA::Char_out CharType_out;
   extern CORBA::TypeCode_ptr _tc_CharType;
   typedef CORBA::LongLong LongLongType;
   typedef CORBA::LongLong_out LongLongType_out;
   extern CORBA::TypeCode_ptr _tc_LongLongType;
   typedef CORBA::Long LongType;
   typedef CORBA::Long_out LongType_out;
   extern CORBA::TypeCode_ptr _tc_LongType;
   typedef CORBA::Short ShortType;
   typedef CORBA::Short_out ShortType_out;
   extern CORBA::TypeCode_ptr _tc_ShortType;
   typedef CORBA::ULongLong ULongLongType;
   typedef CORBA::ULongLong_out ULongLongType_out;
   extern CORBA::TypeCode_ptr _tc_ULongLongType;
   typedef CORBA::ULong ULongType;
   typedef CORBA::ULong_out ULongType_out;
   extern CORBA::TypeCode_ptr _tc_ULongType;
   typedef CORBA::UShort UShortType;
   typedef CORBA::UShort_out UShortType_out;
   extern CORBA::TypeCode_ptr _tc_UShortType;
   typedef CORBA::Float FloatType;
   typedef CORBA::Float_out FloatType_out;
   extern CORBA::TypeCode_ptr _tc_FloatType;
   typedef CORBA::Double DoubleType;
   typedef CORBA::Double_out DoubleType_out;
   extern CORBA::TypeCode_ptr _tc_DoubleType;
   typedef CORBA::Char* StringType;
   typedef CORBA::String_var StringType_var;
   typedef CORBA::String_out StringType_out;
   extern CORBA::TypeCode_ptr _tc_StringType;
   typedef CORBA::Octet OctetType;
   typedef CORBA::Octet_out OctetType_out;
   extern CORBA::TypeCode_ptr _tc_OctetType;
}





#endif 
